export const UPDATE_TOGGLE_SWITCH = "UPDATE_TOGGLE_SWITCH";
export const NAVIGATE_BACKWARD = "NAVIGATE_BACKWARD";
export const NAVIGATE_FORWARD = "NAVIGATE_FORWARD";
export const RESET_STATE = "RESET_STATE";
export const SAVE_LINK_REQUEST = "SAVE_LINK_REQUEST";
export const SAVE_LINK_SUCCESS = "SAVE_LINK_SUCCESS";
export const SAVE_LINK_ERROR = "SAVE_LINK_ERROR";
