export const NAVIGATE_BACK = 'NAVIGATE_BACK';
export const NAVIGATE_FORWARD = 'NAVIGATE_FORWARD';
export const UPDATE_FORM = 'UPDATE_FORM';
export const RESET_FORM = 'RESET_FORM';
export const SET_INPUT_ERROR = 'SET_INPUT_ERROR';
export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';
